# trees/src/smd/CMakeLists.txt                                 -*-CMake-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

add_subdirectory(conceptmap)
add_subdirectory(fixpoint)
add_subdirectory(ranges)
add_subdirectory(thunk)
add_subdirectory(tree)
add_subdirectory(typeclass)
add_subdirectory(ziplist)
