#ifndef INCLUDE_SMD_TYPECLASS_TEST_TEST_MONOIDS_HPP
#define INCLUDE_SMD_TYPECLASS_TEST_TEST_MONOIDS_HPP

#include <smd/typeclass/test/test_support.hpp>

#endif  // INCLUDE_SMD_TYPECLASS_TEST_TEST_MONOIDS_HPP
